### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by paulpela** [tannerdsilva/SwiftSlash#1]
For an ambitious tool like this one, it would be good if you could ensure its continuing correctness by adding unit tests. Please consider adding those.

**Comment by tannerdsilva** [comment]
This is a great point, thank you for your feedback.

I have a basic test case rigged up on my development environment....I can absolutely get this (and additional tests) packaged in for the next point release.

**Comment by tannerdsilva** [comment]
Comprehensive unit tests have been added to the project with release `2.2.2`. Apologies this took so long. 

I have three unit tests to cover all the core functionality of the framework (for now). These unit tests are concurrent in nature, and ensure that SwiftSlash produces the expected result - even under **very** intense concurrent workloads.

Thanks for your constructive feedback in improving SwiftSlash.
