### ISSUE TITLE
Should we use the Dev branch or main?

### ISSUE THREAD

**Issue by majortom64** [tannerdsilva/SwiftSlash#10]
Saw that Main has not been updated for 2 years, but Dev is only two weeks old and wanted to know how stable Dev is and if you would like people to try it out?

**Comment by tannerdsilva** [comment]
Hey,

Thanks for your interest in the project. You are correct, the main branch has not seen a new release in 14 months, however, this will be changing in the next few hours, as I prepare to push v3.4. And as you can see, there has been plenty of massive improvements under development in the dev branches.

I dont love to leave my projects this long without a release, however, the current version has been so stable (in my heavy use of it), that most of my focus in the development branches are focused on larger changes that would come with a v4.0.

I would say v4.0 is 85% developed, most of the remaining work is just extensive testing and integration.

I take stability on this project very seriously, and do not recommend deviating from the release tags. However, I develop in the open, and you are welcome to take a look and test whatever you would like :)
