### ISSUE TITLE
Build failed on Xcode 15 Beta 1

### ISSUE THREAD

**Issue by iwecon** [tannerdsilva/SwiftSlash#13]
`May be just a bug, the follow-up will continue to pay attention to.`

Build failed: 
```swift
Command SwiftCompile failed with a nonzero exit code.
```

Env:
* Xcode 15 Beta 1
* `macOS 14.0 Beta 1` or `macOS 13.3.1`

![CleanShot 2023-06-06 at 23 43 59](https://github.com/tannerdsilva/SwiftSlash/assets/16604027/63112a5f-44bf-4a6f-a219-d9034d345489)

**Comment by tannerdsilva** [comment]
Appreciate the feedback here, its good for me to have this on my radar (my attention is not in any Apple beta this year sadly).

This kinda looks like a bunch of buggy Xcode garbage to me.....but I certainly will be watching closely through the summer to ensure this isn't anything I need to take action in.

SwiftSlash needs some work to support Swift 6, but I believe that is next years development....

**Comment by iwecon** [comment]
Fix in Xcode 15 beta 3 (15A5195k).
