### ISSUE TITLE
Typo in example code in readme

### ISSUE THREAD

**Issue by jhoughjr** [tannerdsilva/SwiftSlash#9]
this line
```swift
zfsProcessInterface.write(stdin:"hello".data(using.utf8)!)
```
should be
```swift
zfsProcessInterface.write(stdin:"hello".data(using:.utf8)!)
```

**Comment by jhoughjr** [comment]
I also just noticed ```swift
 //handle lines of stdout as they come in
            var datasetLines = [Data]()
            for await outputLine in await zfsProcessInterface.stdout {
                print("dataset found: \( String(data:outputLine, encoding:.utf8) )")
                datasetLines.append(outputLine)
            }``` += complained Data vs Data.Element that append did not

**Comment by tannerdsilva** [comment]
Thank you for the correction. This is being updated in the upcoming v3.4 release.
